spring:
  application:
    name: security-spring
  security:
    user:
      name: ravi
      password: raviraj
  datasource:
    url: jdbc:mysql://localhost:3306/librarystudent
    username: root
    password: Raviraj@5475
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
